export const fallbackDepartments = [
  { departmentId: 0, displayName: "All departments" },
  { departmentId: 11, displayName: "European Paintings" },
  { departmentId: 6, displayName: "Asian Art" },
  { departmentId: 9, displayName: "Drawings and Prints" },
  { departmentId: 1, displayName: "The American Wing" },
  { departmentId: 13, displayName: "Greek and Roman Art" },
  { departmentId: 14, displayName: "Islamic Art" },
  { departmentId: 4, displayName: "Arms and Armor" },
  { departmentId: 19, displayName: "Photographs" },
  { departmentId: 21, displayName: "Modern Art" }
];

export const fallbackWorks = [
  {
    id: 437881,
    title: "Young Woman with a Water Pitcher",
    cardTitle: "Young Woman with a Water Pitcher",
    artist: "Johannes Vermeer",
    date: "ca. 1662",
    medium: "Oil on canvas",
    department: "European Paintings",
    culture: "Dutch",
    classification: "Paintings",
    type: "Painting",
    image: "./assets/art/437881.jpg",
    localImage: "./assets/art/437881.jpg",
    fullImage: "./assets/art/437881.jpg",
    ratio: 1067 / 1200,
    objectURL: "https://www.metmuseum.org/art/collection/search/437881",
    layout: { span: 2, start: 2, offset: 0 }
  },
  {
    id: 253370,
    title: "Marble statue of a kouros (youth)",
    cardTitle: "Marble Kouros",
    artist: "Greek, Attic",
    date: "ca. 590-580 BCE",
    medium: "Marble, Naxian",
    department: "Greek and Roman Art",
    culture: "Greek",
    classification: "Sculpture",
    type: "Sculpture",
    image: "./assets/art/253370.jpg",
    localImage: "./assets/art/253370.jpg",
    fullImage: "./assets/art/253370.jpg",
    ratio: 806 / 1200,
    objectURL: "https://www.metmuseum.org/art/collection/search/253370",
    layout: { span: 2, start: 4, offset: 72 }
  },
  {
    id: 10497,
    title: "View from Mount Holyoke, Northampton, Massachusetts, after a Thunderstorm",
    cardTitle: "The Oxbow",
    artist: "Thomas Cole",
    date: "1836",
    medium: "Oil on canvas",
    department: "The American Wing",
    culture: "American",
    classification: "Paintings",
    type: "Painting",
    image: "./assets/art/10497.jpg",
    localImage: "./assets/art/10497.jpg",
    fullImage: "./assets/art/10497.jpg",
    ratio: 1200 / 820,
    objectURL: "https://www.metmuseum.org/art/collection/search/10497",
    layout: { span: 3, start: 6, offset: 14 }
  },
  {
    id: 339683,
    title: "The Octagonal Room in the Small Baths at the Villa of Hadrian",
    cardTitle: "Octagonal Room Study",
    artist: "Giovanni Battista Piranesi",
    date: "ca. 1777",
    medium: "Red and black chalk",
    department: "Drawings and Prints",
    culture: "Italian",
    classification: "Drawings",
    type: "Drawing",
    image: "./assets/art/339683.jpg",
    localImage: "./assets/art/339683.jpg",
    fullImage: "./assets/art/339683.jpg",
    ratio: 1200 / 864,
    objectURL: "https://www.metmuseum.org/art/collection/search/339683",
    layout: { span: 2, start: 8, offset: 34 }
  },
  {
    id: 467642,
    title: "The Unicorn Rests in a Garden",
    cardTitle: "The Unicorn Rests in a Garden",
    artist: "South Netherlandish weaver",
    date: "1495-1505",
    medium: "Wool, silk, silver, and gilt wefts",
    department: "Medieval Art and The Cloisters",
    culture: "French / South Netherlandish",
    classification: "Textiles",
    type: "Textile",
    image: "./assets/art/467642.jpg",
    localImage: "./assets/art/467642.jpg",
    fullImage: "./assets/art/467642.jpg",
    ratio: 847 / 1200,
    objectURL: "https://www.metmuseum.org/art/collection/search/467642",
    layout: { span: 2, start: 10, offset: 86 }
  },
  {
    id: 444713,
    title: "Mosque Lamp of Amir Ahmad al-Mihmandar",
    cardTitle: "Mosque Lamp",
    artist: "Mamluk period maker",
    date: "ca. 1325",
    medium: "Enameled and gilded glass",
    department: "Islamic Art",
    culture: "Egypt or Syria",
    classification: "Glass",
    type: "Glass",
    image: "./assets/art/444713.jpg",
    localImage: "./assets/art/444713.jpg",
    fullImage: "./assets/art/444713.jpg",
    ratio: 1,
    objectURL: "https://www.metmuseum.org/art/collection/search/444713",
    layout: { span: 2, start: 0, offset: 325 }
  },
  {
    id: 35721,
    title: "Armor (Gusoku)",
    cardTitle: "Armor (Gusoku)",
    artist: "Saotome Ietada and Myochin Munesuke",
    date: "16th and 18th centuries",
    medium: "Iron, lacquer, silk, and gilt copper",
    department: "Arms and Armor",
    culture: "Japanese",
    classification: "Armor",
    type: "Armor",
    image: "./assets/art/35721.jpg",
    localImage: "./assets/art/35721.jpg",
    fullImage: "./assets/art/35721.jpg",
    ratio: 686 / 1200,
    objectURL: "https://www.metmuseum.org/art/collection/search/35721",
    layout: { span: 2, start: 1, offset: 255 }
  },
  {
    id: 436634,
    title: "A Vase of Flowers",
    cardTitle: "A Vase of Flowers",
    artist: "Margareta Haverman",
    date: "1716",
    medium: "Oil on wood",
    department: "European Paintings",
    culture: "Dutch",
    classification: "Paintings",
    type: "Still life",
    image: "./assets/art/436634.jpg",
    localImage: "./assets/art/436634.jpg",
    fullImage: "./assets/art/436634.jpg",
    ratio: 920 / 1200,
    objectURL: "https://www.metmuseum.org/art/collection/search/436634",
    layout: { span: 3, start: 3, offset: 30 }
  },
  {
    id: 45434,
    title: "Under the Wave off Kanagawa",
    cardTitle: "Under the Wave off Kanagawa",
    artist: "Katsushika Hokusai",
    date: "ca. 1830-32",
    medium: "Woodblock print; ink and color on paper",
    department: "Asian Art",
    culture: "Japanese",
    classification: "Prints",
    type: "Print",
    image: "./assets/art/45434.jpg",
    localImage: "./assets/art/45434.jpg",
    fullImage: "./assets/art/45434.jpg",
    ratio: 1200 / 807,
    objectURL: "https://www.metmuseum.org/art/collection/search/45434",
    layout: { span: 2, start: 6, offset: 38 }
  },
  {
    id: 39571,
    title: "Bowl",
    cardTitle: "Buncheong Bowl",
    artist: "Korean maker",
    date: "first half of the 16th century",
    medium: "Buncheong ware with white slip",
    department: "Asian Art",
    culture: "Korea, Joseon dynasty",
    classification: "Ceramics",
    type: "Ceramic",
    image: "./assets/art/39571.jpg",
    localImage: "./assets/art/39571.jpg",
    fullImage: "./assets/art/39571.jpg",
    ratio: 1200 / 890,
    objectURL: "https://www.metmuseum.org/art/collection/search/39571",
    layout: { span: 2, start: 8, offset: 35 }
  },
  {
    id: 12127,
    title: "Madame X (Madame Pierre Gautreau)",
    cardTitle: "Madame X",
    artist: "John Singer Sargent",
    date: "1883-84",
    medium: "Oil on canvas",
    department: "The American Wing",
    culture: "American",
    classification: "Paintings",
    type: "Portrait",
    image: "./assets/art/12127.jpg",
    localImage: "./assets/art/12127.jpg",
    fullImage: "./assets/art/12127.jpg",
    ratio: 701 / 1200,
    objectURL: "https://www.metmuseum.org/art/collection/search/12127",
    layout: { span: 2, start: 10, offset: 32 }
  },
  {
    id: 438817,
    title: "The Dance Class",
    cardTitle: "The Dance Class",
    artist: "Edgar Degas",
    date: "1874",
    medium: "Oil on canvas",
    department: "European Paintings",
    culture: "French",
    classification: "Paintings",
    type: "Painting",
    image: "./assets/art/438817.jpg",
    localImage: "./assets/art/438817.jpg",
    fullImage: "./assets/art/438817.jpg",
    ratio: 1113 / 1200,
    objectURL: "https://www.metmuseum.org/art/collection/search/438817",
    layout: { span: 3, start: 0, offset: 36 }
  },
  {
    id: 459052,
    title: "A Goldsmith in his Shop",
    cardTitle: "A Goldsmith in his Shop",
    artist: "Petrus Christus",
    date: "1449",
    medium: "Oil on oak panel",
    department: "Robert Lehman Collection",
    culture: "Netherlandish",
    classification: "Paintings",
    type: "Painting",
    image: "./assets/art/459052.jpg",
    localImage: "./assets/art/459052.jpg",
    fullImage: "./assets/art/459052.jpg",
    ratio: 1041 / 1200,
    objectURL: "https://www.metmuseum.org/art/collection/search/459052",
    layout: { span: 2, start: 2, offset: 26 }
  },
  {
    id: 469963,
    title: "Manuscript Leaf with the Last Judgment",
    cardTitle: "Last Judgment Manuscript Leaf",
    artist: "French illuminator",
    date: "ca. 1400",
    medium: "Tempera and gold on parchment",
    department: "Medieval Art and The Cloisters",
    culture: "French",
    classification: "Manuscripts",
    type: "Manuscript",
    image: "./assets/art/469963.jpg",
    localImage: "./assets/art/469963.jpg",
    fullImage: "./assets/art/469963.jpg",
    ratio: 809 / 1200,
    objectURL: "https://www.metmuseum.org/art/collection/search/469963",
    layout: { span: 2, start: 4, offset: 34 }
  },
  {
    id: 436535,
    title: "Wheat Field with Cypresses",
    cardTitle: "Wheat Field with Cypresses",
    artist: "Vincent van Gogh",
    date: "1889",
    medium: "Oil on canvas",
    department: "European Paintings",
    culture: "Dutch",
    classification: "Paintings",
    type: "Painting",
    image: "./assets/art/436535.jpg",
    localImage: "./assets/art/436535.jpg",
    fullImage: "./assets/art/436535.jpg",
    ratio: 1200 / 955,
    objectURL: "https://www.metmuseum.org/art/collection/search/436535",
    layout: { span: 2, start: 6, offset: 30 }
  },
  {
    id: 444408,
    title: "Astrolabe",
    cardTitle: "Astrolabe",
    artist: "Umar ibn Yusuf ibn Umar",
    date: "1291 CE",
    medium: "Brass, cast, hammered, pierced, and inlaid",
    department: "Islamic Art",
    culture: "Yemeni",
    classification: "Scientific Instruments",
    type: "Object",
    image: "./assets/art/444408.jpg",
    localImage: "./assets/art/444408.jpg",
    fullImage: "./assets/art/444408.jpg",
    ratio: 899 / 1200,
    objectURL: "https://www.metmuseum.org/art/collection/search/444408",
    layout: { span: 2, start: 8, offset: 33 }
  },
  {
    id: 901858,
    title: "Tsujigahana Textile Fragment with Wild Ginger Leaves and Sprays of Wisteria",
    cardTitle: "Tsujigahana Textile Fragment",
    artist: "",
    date: "second half 16th century",
    medium: "Textile fragment",
    department: "Asian Art",
    culture: "Japan",
    classification: "Textiles-Painted and Dyed",
    type: "Textile fragment",
    image: "",
    localImage: "",
    fullImage: "",
    ratio: 1,
    objectURL: "https://www.metmuseum.org/art/collection/search/901858",
    layout: { span: 2, start: 10, offset: 18 }
  }
].map((work) => ({
  ...work,
  hasImage: Boolean(work.image),
  source: "fallback",
  gallery: "Collection record",
  credit: "The Metropolitan Museum of Art Open Access"
}));
